### ISSUE TITLE
라이브러리 이름 변경 건에 대하여

### ISSUE THREAD

**Issue by devproje** [highright1234/minipaper#2]
이 라이브러리의 이름을 살짝 건전한거로 변경하면 좋을거 같습니다만... minimine이라던지 miniextension 같은걸로 바꿔도 괜찮지 않을까요?

**Comment by R2turnTrue** [comment]
동의합니다

**Comment by devproje** [comment]
이슈 왜 씹어요?

**Comment by devproje** [comment]
유저들의 입장은 안중요해요?

**Comment by devproje** [comment]
하라 공화국이네

**Comment by MineStarAS** [comment]
변경할 이름 추천 합니다.
추천할 이름은 바로,
Watashiga_shinda_ato_bisyonenni_tensyooshitaga_osananajimiga_yanderedatta
(내가 죽은뒤 미소년으로 전생되었지만 소꿉친구가 얀데레였다)
입니다

**Comment by highright1234** [comment]
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by ghost** [comment]
@highright1234 craticalized
없는단어고 crystalized에서 비틀어봤음
추천해봄

**Comment by myoun** [comment]
tinygame

**Comment by yuhan3958** [comment]
대충 minipaper 어떤가요

**Comment by devproje** [comment]
gamekernel or minekernel

**Comment by ghost** [comment]
그냥 util하삼 어차피 콤월드쪽도 util임 ㅋㅋㅋㅋㅋ

**Comment by dytroc** [comment]
> 그냥 util하삼 어차피 콤월드쪽도 util임 ㅋㅋㅋㅋㅋ

이에 동의합니다.

**Comment by highright1234** [comment]
주변에서 다 바꾸라고 하긴 하지만 뭔가 결이 비슷하며 입에 착 달라붙는 느낌이 없어유 ㅋㅋㅋㅋㅋㅋㅋ
모든게 다 쇼토코노코에 비해서 2% 부족한 느낌이랄까(~~그냥 제 취향입니다~~)

**Comment by highright1234** [comment]
근데 진짜로 궁금한데 이 이름이면 기능 좋아도 쓰기 싫어지나요?(그저 설문용)

**Comment by ghost** [comment]
팩트 꽂으면 그냥 안써요

**Comment by devproje** [comment]
> 주변에서 다 바꾸라고 하긴 하지만 뭔가 결이 비슷하며 입에 착 달라붙는 느낌이 없어유 ㅋㅋㅋㅋㅋㅋㅋ
> 모든게 다 쇼토코노코에 비해서 2% 부족한 느낌이랄까(~~그냥 제 취향입니다~~)

걍 죽어

**Comment by devproje** [comment]
> 근데 진짜로 궁금한데 이 이름이면 기능 좋아도 쓰기 싫어지나요?(그저 설문용)

놀이터에서도 탈탈 털었는데도 또 정신 못차리네;;

**Comment by MineStarAS** [comment]
근데 애초에 오토코노코 라는 단어의 상위 클라스가 쇼타인데 이름을 저렇게 지으면 상속 중복이지 않나요?

**Comment by highright1234** [comment]
하모씨 결국 쇼토코노코로 계속할것같아 개발자들 충격

**Comment by devproje** [comment]
> 하모씨 결국 쇼토코노코로 계속할것같아 개발자들 충격

묻는다?

**Comment by ghost** [comment]
손절할게요

**Comment by highright1234** [comment]
아

**Comment by devproje** [comment]
![image](https://user-images.githubusercontent.com/53290556/188437526-260b3b88-d03b-46c0-bbdc-0a0a27664bdb.png)
미치셨습니까 휴먼

**Comment by highright1234** [comment]
```
fun main() {
    listOf(
        "minimine",
        "minekernel",
        "craticalized",
        "tinygame",
        "minipaper",
        "budaejjigae",
        "gameutil",
        "shotokonoko",
        "instancy"
    ).random().let(::println)
}

minipaper
```
랜덤뽑기로 인해 minipaper가 뽑혔습니당

**Comment by highright1234** [comment]
~~다음에는 협상따윈 없습니다~~
